const path = require('path');
const ROOT = path.resolve(__dirname, '../..');

module.exports = {
  contactoeficaz: {
    displayName: 'ContactoEficaz',
    color: '#2563eb',
    automations: {
      mibanco: {
        displayName: 'Mibanco — Reporte Banco',
        color: '#0066cc',
        script: path.join(ROOT, 'src/index.js'),
        lastRunFile: path.join(ROOT, 'descargas/last_run.json'),
        historyFile: path.join(ROOT, 'descargas/history_mibanco.json'),
        scheduleKey: 'MIBANCO_SCHEDULE_TIME',
        configSchema: [
          { key: 'MIBANCO_URL',            label: 'URL FileTransfer',               type: 'text',     secret: false },
          { key: 'MIBANCO_USER',           label: 'Usuario',                        type: 'text',     secret: false },
          { key: 'MIBANCO_PASS',           label: 'Contraseña',                     type: 'password', secret: true  },
          { key: 'MIBANCO_NOTAS',          label: 'Notas de carga',                 type: 'text',     secret: false },
          { key: 'MIBANCO_SCHEDULE_TIME',  label: 'Horario de ejecución (hora Perú)', type: 'time',   secret: false },
        ],
      },
      surgir: {
        displayName: 'Surgir — Reporte Banco',
        color: '#e85d00',
        script: path.join(ROOT, 'src/clientes/contactoeficaz/surgir/rpa/index.js'),
        lastRunFile: path.join(ROOT, 'descargas/last_run_surgir.json'),
        historyFile: path.join(ROOT, 'descargas/history_surgir.json'),
        scheduleKey: 'SURGIR_SCHEDULE_TIME',
        configSchema: [
          { key: 'SURGIR_SMTP_HOST',       label: 'Servidor SMTP',                    type: 'text',     secret: false },
          { key: 'SURGIR_SMTP_PORT',       label: 'Puerto SMTP',                      type: 'number',   secret: false },
          { key: 'SURGIR_SMTP_USER',       label: 'Usuario SMTP',                     type: 'email',    secret: false },
          { key: 'SURGIR_SMTP_PASS',       label: 'Contraseña SMTP',                  type: 'password', secret: true  },
          { key: 'SURGIR_MAIL_TO',         label: 'Destinatarios (separados por ,)',  type: 'text',     secret: false },
          { key: 'SURGIR_SCHEDULE_TIME',   label: 'Horario de ejecución (hora Perú)', type: 'time',     secret: false },
        ],
      },
      wolkvox: {
        displayName: 'Wolkvox — Ingesta Llamadas',
        color: '#7c3aed',
        type: 'ingesta',
        script: path.join(ROOT, 'src/clientes/contactoeficaz/ingesta/wolkvox.js'),
        lastRunFile: path.join(ROOT, 'descargas/last_run_wolkvox.json'),
        historyFile: path.join(ROOT, 'descargas/history_wolkvox.json'),
        scheduleKeys: ['WOLKVOX_SCHEDULE_MANANA', 'WOLKVOX_SCHEDULE_TARDE'],
        configSchema: [
          { key: 'MCOB_DB_SERVER',           label: 'SQL Server (host\\instancia)',                    type: 'text',     secret: false },
          { key: 'MCOB_DB_DATABASE',         label: 'Base de datos',                                  type: 'text',     secret: false },
          { key: 'MCOB_DB_USER',             label: 'Usuario BD',                                     type: 'text',     secret: false },
          { key: 'MCOB_DB_PASS',             label: 'Contraseña BD',                                  type: 'password', secret: true  },
          { key: 'KEY_CRYPT',                label: 'Clave de descifrado',                            type: 'password', secret: true  },
          { key: 'WOLKVOX_SCHEDULE_MANANA',  label: 'Horario mañana — datos de ayer (hora Perú)',     type: 'time',     secret: false, hint: 'Ejecución tipo 1: se activa antes del mediodía y procesa llamadas del día anterior' },
          { key: 'WOLKVOX_SCHEDULE_TARDE',   label: 'Horario tarde — datos de hoy (hora Perú)',       type: 'time',     secret: false, hint: 'Ejecución tipo 2: se activa desde el mediodía y procesa llamadas del día actual' },
          { key: 'NOTIF_SMTP_HOST',         label: 'SMTP host (notificaciones)',        type: 'text',     secret: false },
          { key: 'NOTIF_SMTP_PORT',         label: 'SMTP puerto',                       type: 'number',   secret: false },
          { key: 'NOTIF_SMTP_USER',         label: 'SMTP usuario',                      type: 'email',    secret: false },
          { key: 'NOTIF_SMTP_PASS',         label: 'SMTP contraseña',                   type: 'password', secret: true  },
          { key: 'NOTIF_MAIL_TO',           label: 'Destinatarios (separados por ,)',   type: 'text',     secret: false },
        ],
      },
      ipbusiness: {
        displayName: 'IPBusiness — Ingesta Llamadas',
        color: '#059669',
        type: 'ingesta',
        script: path.join(ROOT, 'src/clientes/contactoeficaz/ingesta/ipbusiness.js'),
        lastRunFile: path.join(ROOT, 'descargas/last_run_ipbusiness.json'),
        historyFile: path.join(ROOT, 'descargas/history_ipbusiness.json'),
        scheduleKey: 'IPB_SCHEDULE_TIME',
        configSchema: [
          { key: 'IPB_URL',                 label: 'URLs IPBusiness (separadas por ,)', type: 'text',     secret: false, hint: 'Ej: http://ce1.ipb.pe/.../archivo.php,http://ce2.ipb.pe/.../archivo.php' },
          { key: 'MCOB_DB_SERVER',          label: 'SQL Server (host\\instancia)',      type: 'text',     secret: false },
          { key: 'MCOB_DB_DATABASE',        label: 'Base de datos',                    type: 'text',     secret: false },
          { key: 'MCOB_DB_USER',            label: 'Usuario BD',                       type: 'text',     secret: false },
          { key: 'MCOB_DB_PASS',            label: 'Contraseña BD',                    type: 'password', secret: true  },
          { key: 'KEY_CRYPT',               label: 'Clave de descifrado',              type: 'password', secret: true  },
          { key: 'IPB_SCHEDULE_TIME',       label: 'Horario de ejecución (hora Perú)', type: 'time',     secret: false },
          { key: 'NOTIF_SMTP_HOST',         label: 'SMTP host (notificaciones)',        type: 'text',     secret: false },
          { key: 'NOTIF_SMTP_PORT',         label: 'SMTP puerto',                       type: 'number',   secret: false },
          { key: 'NOTIF_SMTP_USER',         label: 'SMTP usuario',                      type: 'email',    secret: false },
          { key: 'NOTIF_SMTP_PASS',         label: 'SMTP contraseña',                   type: 'password', secret: true  },
          { key: 'NOTIF_MAIL_TO',           label: 'Destinatarios (separados por ,)',   type: 'text',     secret: false },
        ],
      },
    },
  },
};
